### ISSUE TITLE
XCode 16: Preview does not load, when using Google places via Swift package manager(SPM).

### ISSUE THREAD

**Issue by jaymeen-unadkat-differenz** [googlemaps/ios-places-sdk#27]
I am encountering an issue when trying to load the SwiftUI preview in Xcode.

The preview fails to load, and the following error message is displayed:

path: /Users/name/Library/Developer/Xcode/DerivedData/ProjectName-dwdmqbhdmhmkapecokpiqgxokpix/Build/Products/Debug-iphonesimulator/GooglePlaces.a

It appears to be related to the GooglePlaces library. I’ve already integrated it using Swift Package Manager (SPM).

Has anyone else experienced a similar issue or found a solution for this? Any help would be greatly appreciated!

#### Environment details

1. Google Places SDK
2. MacOS Sequoia, Xcode 16
3. Library version 9.2.0

#### Steps to reproduce

  1. Try to load the preview, while using the Google Places SDK using SPM

#### Stack trace
```

FailedToLaunchAppError: Failed to launch com.app.<app_name>

|  [Remote] JITError  
|  
|  ==================================  
|  
|  |  [Remote] CouldNotLoadInputStaticArchiveFile: Could not load static archive during preview:  
|  |  /Library/Developer/Xcode/DerivedData/<project_name>/Build/Products/Debug-iphonesimulator/GooglePlaces.a  
|  |  
|  |  path: /Library/Developer/Xcode/DerivedData/<project_name>/Build/Products/Debug-iphonesimulator/GooglePlaces.a  
|  |  
|  |  ==================================  
|  |  
|  |  |  [Remote] XOJITError  
|  |  |  
|  |  |  XOJITError: x86_64 slice of  
|  |  |  /Library/Developer/Xcode/DerivedData/<project_name>/Build/Products/Debug-iphonesimulator/GooglePlaces.a does not contain an archive






```

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by NekaFTW** [comment]
![](https://github.com/user-attachments/assets/fa39cf0b-5c26-4547-bac2-e35aa1ad21bb)

Try to activate `Editor > Canvas > Use Legacy Previews Execution` (Canvas must be open).
Hope it helps :)

**Comment by jaymeen-unadkat-differenz** [comment]
@NekaFTW Works wonderfully, thanks!

**Comment by Joebayld** [comment]
Is there plans to make this work with the modern previews execution?
